server:
  port: 8888

spring:
  activemq:
    broker-url: tcp://192.168.99.100:61617 # mq服务器地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false = Queue   true = Topic  默认 false

#队列名称
#myqueue: boot-activemq-queue
myqueue: boot-activemq-topic